// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __present_rounds_sbbkb_H__
#define __present_rounds_sbbkb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct present_rounds_sbbkb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(present_rounds_sbbkb_ram) {
        ram[0] = "0b11000000";
        ram[1] = "0b01010000";
        ram[2] = "0b01100000";
        ram[3] = "0b10110000";
        ram[4] = "0b10010000";
        ram[5] = "0b00000000";
        ram[6] = "0b10100000";
        ram[7] = "0b11010000";
        ram[8] = "0b00110000";
        ram[9] = "0b11100000";
        ram[10] = "0b11110000";
        ram[11] = "0b10000000";
        ram[12] = "0b01000000";
        ram[13] = "0b01110000";
        ram[14] = "0b00010000";
        ram[15] = "0b00100000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(present_rounds_sbbkb) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


present_rounds_sbbkb_ram* meminst;


SC_CTOR(present_rounds_sbbkb) {
meminst = new present_rounds_sbbkb_ram("present_rounds_sbbkb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~present_rounds_sbbkb() {
    delete meminst;
}


};//endmodule
#endif
