// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "present.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic present::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic present::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> present::ap_ST_fsm_state1 = "1";
const sc_lv<4> present::ap_ST_fsm_state2 = "10";
const sc_lv<4> present::ap_ST_fsm_state3 = "100";
const sc_lv<4> present::ap_ST_fsm_state4 = "1000";
const sc_lv<32> present::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> present::ap_const_lv1_0 = "0";
const sc_lv<1> present::ap_const_lv1_1 = "1";
const sc_lv<2> present::ap_const_lv2_0 = "00";
const sc_lv<2> present::ap_const_lv2_2 = "10";
const sc_lv<2> present::ap_const_lv2_3 = "11";
const sc_lv<2> present::ap_const_lv2_1 = "1";
const sc_lv<32> present::ap_const_lv32_1 = "1";
const sc_lv<32> present::ap_const_lv32_2 = "10";
const sc_lv<32> present::ap_const_lv32_3 = "11";
const sc_lv<32> present::ap_const_lv32_50 = "1010000";
const sc_lv<32> present::ap_const_lv32_8F = "10001111";
const bool present::ap_const_boolean_1 = true;

present::present(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_present_rounds_fu_80 = new present_rounds("grp_present_rounds_fu_80");
    grp_present_rounds_fu_80->ap_clk(ap_clk);
    grp_present_rounds_fu_80->ap_rst(ap_rst_n_inv);
    grp_present_rounds_fu_80->ap_start(grp_present_rounds_fu_80_ap_start);
    grp_present_rounds_fu_80->ap_done(grp_present_rounds_fu_80_ap_done);
    grp_present_rounds_fu_80->ap_idle(grp_present_rounds_fu_80_ap_idle);
    grp_present_rounds_fu_80->ap_ready(grp_present_rounds_fu_80_ap_ready);
    grp_present_rounds_fu_80->plain_V(p_Result_s_reg_126);
    grp_present_rounds_fu_80->key_V(tmp_82_reg_131);
    grp_present_rounds_fu_80->ap_return(grp_present_rounds_fu_80_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state4);
    sensitive << ( stateOut_data_V_1_ack_in );
    sensitive << ( stateOut_last_V_1_ack_in );

    SC_METHOD(thread_ap_done);
    sensitive << ( stateOut_data_V_1_ack_in );
    sensitive << ( stateOut_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( stateOut_data_V_1_ack_in );
    sensitive << ( stateOut_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_grp_present_rounds_fu_80_ap_start);
    sensitive << ( grp_present_rounds_fu_80_ap_start_reg );

    SC_METHOD(thread_stateIn_TDATA_blk_n);
    sensitive << ( stateIn_data_V_0_state );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_stateIn_TREADY);
    sensitive << ( stateIn_last_V_0_state );

    SC_METHOD(thread_stateIn_data_V_0_ack_in);
    sensitive << ( stateIn_data_V_0_state );

    SC_METHOD(thread_stateIn_data_V_0_ack_out);
    sensitive << ( stateIn_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_stateIn_data_V_0_data_out);
    sensitive << ( stateIn_data_V_0_payload_A );
    sensitive << ( stateIn_data_V_0_payload_B );
    sensitive << ( stateIn_data_V_0_sel );

    SC_METHOD(thread_stateIn_data_V_0_load_A);
    sensitive << ( stateIn_data_V_0_sel_wr );
    sensitive << ( stateIn_data_V_0_state_cmp_full );

    SC_METHOD(thread_stateIn_data_V_0_load_B);
    sensitive << ( stateIn_data_V_0_sel_wr );
    sensitive << ( stateIn_data_V_0_state_cmp_full );

    SC_METHOD(thread_stateIn_data_V_0_sel);
    sensitive << ( stateIn_data_V_0_sel_rd );

    SC_METHOD(thread_stateIn_data_V_0_state_cmp_full);
    sensitive << ( stateIn_data_V_0_state );

    SC_METHOD(thread_stateIn_data_V_0_vld_in);
    sensitive << ( stateIn_TVALID );

    SC_METHOD(thread_stateIn_data_V_0_vld_out);
    sensitive << ( stateIn_data_V_0_state );

    SC_METHOD(thread_stateIn_last_V_0_ack_in);
    sensitive << ( stateIn_last_V_0_state );

    SC_METHOD(thread_stateIn_last_V_0_ack_out);
    sensitive << ( stateIn_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_stateIn_last_V_0_data_out);
    sensitive << ( stateIn_last_V_0_payload_A );
    sensitive << ( stateIn_last_V_0_payload_B );
    sensitive << ( stateIn_last_V_0_sel );

    SC_METHOD(thread_stateIn_last_V_0_load_A);
    sensitive << ( stateIn_last_V_0_sel_wr );
    sensitive << ( stateIn_last_V_0_state_cmp_full );

    SC_METHOD(thread_stateIn_last_V_0_load_B);
    sensitive << ( stateIn_last_V_0_sel_wr );
    sensitive << ( stateIn_last_V_0_state_cmp_full );

    SC_METHOD(thread_stateIn_last_V_0_sel);
    sensitive << ( stateIn_last_V_0_sel_rd );

    SC_METHOD(thread_stateIn_last_V_0_state_cmp_full);
    sensitive << ( stateIn_last_V_0_state );

    SC_METHOD(thread_stateIn_last_V_0_vld_in);
    sensitive << ( stateIn_TVALID );

    SC_METHOD(thread_stateIn_last_V_0_vld_out);
    sensitive << ( stateIn_last_V_0_state );

    SC_METHOD(thread_stateOut_TDATA);
    sensitive << ( stateOut_data_V_1_data_out );

    SC_METHOD(thread_stateOut_TDATA_blk_n);
    sensitive << ( stateOut_data_V_1_state );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_stateOut_TLAST);
    sensitive << ( stateOut_last_V_1_data_out );

    SC_METHOD(thread_stateOut_TVALID);
    sensitive << ( stateOut_last_V_1_state );

    SC_METHOD(thread_stateOut_data_V_1_ack_in);
    sensitive << ( stateOut_data_V_1_state );

    SC_METHOD(thread_stateOut_data_V_1_ack_out);
    sensitive << ( stateOut_TREADY );

    SC_METHOD(thread_stateOut_data_V_1_data_out);
    sensitive << ( stateOut_data_V_1_payload_A );
    sensitive << ( stateOut_data_V_1_payload_B );
    sensitive << ( stateOut_data_V_1_sel );

    SC_METHOD(thread_stateOut_data_V_1_load_A);
    sensitive << ( stateOut_data_V_1_sel_wr );
    sensitive << ( stateOut_data_V_1_state_cmp_full );

    SC_METHOD(thread_stateOut_data_V_1_load_B);
    sensitive << ( stateOut_data_V_1_sel_wr );
    sensitive << ( stateOut_data_V_1_state_cmp_full );

    SC_METHOD(thread_stateOut_data_V_1_sel);
    sensitive << ( stateOut_data_V_1_sel_rd );

    SC_METHOD(thread_stateOut_data_V_1_state_cmp_full);
    sensitive << ( stateOut_data_V_1_state );

    SC_METHOD(thread_stateOut_data_V_1_vld_in);
    sensitive << ( stateOut_data_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_present_rounds_fu_80_ap_done );

    SC_METHOD(thread_stateOut_data_V_1_vld_out);
    sensitive << ( stateOut_data_V_1_state );

    SC_METHOD(thread_stateOut_last_V_1_ack_in);
    sensitive << ( stateOut_last_V_1_state );

    SC_METHOD(thread_stateOut_last_V_1_ack_out);
    sensitive << ( stateOut_TREADY );

    SC_METHOD(thread_stateOut_last_V_1_data_out);
    sensitive << ( stateOut_last_V_1_payload_A );
    sensitive << ( stateOut_last_V_1_payload_B );
    sensitive << ( stateOut_last_V_1_sel );

    SC_METHOD(thread_stateOut_last_V_1_load_A);
    sensitive << ( stateOut_last_V_1_sel_wr );
    sensitive << ( stateOut_last_V_1_state_cmp_full );

    SC_METHOD(thread_stateOut_last_V_1_load_B);
    sensitive << ( stateOut_last_V_1_sel_wr );
    sensitive << ( stateOut_last_V_1_state_cmp_full );

    SC_METHOD(thread_stateOut_last_V_1_sel);
    sensitive << ( stateOut_last_V_1_sel_rd );

    SC_METHOD(thread_stateOut_last_V_1_state_cmp_full);
    sensitive << ( stateOut_last_V_1_state );

    SC_METHOD(thread_stateOut_last_V_1_vld_in);
    sensitive << ( stateOut_data_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_present_rounds_fu_80_ap_done );

    SC_METHOD(thread_stateOut_last_V_1_vld_out);
    sensitive << ( stateOut_last_V_1_state );

    SC_METHOD(thread_tmp_82_fu_116_p1);
    sensitive << ( stateIn_data_V_0_data_out );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( stateIn_data_V_0_vld_out );
    sensitive << ( stateOut_data_V_1_ack_in );
    sensitive << ( stateOut_last_V_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_present_rounds_fu_80_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0001";
    stateIn_data_V_0_sel_rd = SC_LOGIC_0;
    stateIn_data_V_0_sel_wr = SC_LOGIC_0;
    stateIn_data_V_0_state = "00";
    stateIn_last_V_0_sel_rd = SC_LOGIC_0;
    stateIn_last_V_0_sel_wr = SC_LOGIC_0;
    stateIn_last_V_0_state = "00";
    stateOut_data_V_1_sel_rd = SC_LOGIC_0;
    stateOut_data_V_1_sel_wr = SC_LOGIC_0;
    stateOut_data_V_1_state = "00";
    stateOut_last_V_1_sel_rd = SC_LOGIC_0;
    stateOut_last_V_1_sel_wr = SC_LOGIC_0;
    stateOut_last_V_1_state = "00";
    grp_present_rounds_fu_80_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "present_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, stateIn_TDATA, "(port)stateIn_TDATA");
    sc_trace(mVcdFile, stateIn_TVALID, "(port)stateIn_TVALID");
    sc_trace(mVcdFile, stateIn_TREADY, "(port)stateIn_TREADY");
    sc_trace(mVcdFile, stateIn_TLAST, "(port)stateIn_TLAST");
    sc_trace(mVcdFile, stateOut_TDATA, "(port)stateOut_TDATA");
    sc_trace(mVcdFile, stateOut_TVALID, "(port)stateOut_TVALID");
    sc_trace(mVcdFile, stateOut_TREADY, "(port)stateOut_TREADY");
    sc_trace(mVcdFile, stateOut_TLAST, "(port)stateOut_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, stateIn_data_V_0_data_out, "stateIn_data_V_0_data_out");
    sc_trace(mVcdFile, stateIn_data_V_0_vld_in, "stateIn_data_V_0_vld_in");
    sc_trace(mVcdFile, stateIn_data_V_0_vld_out, "stateIn_data_V_0_vld_out");
    sc_trace(mVcdFile, stateIn_data_V_0_ack_in, "stateIn_data_V_0_ack_in");
    sc_trace(mVcdFile, stateIn_data_V_0_ack_out, "stateIn_data_V_0_ack_out");
    sc_trace(mVcdFile, stateIn_data_V_0_payload_A, "stateIn_data_V_0_payload_A");
    sc_trace(mVcdFile, stateIn_data_V_0_payload_B, "stateIn_data_V_0_payload_B");
    sc_trace(mVcdFile, stateIn_data_V_0_sel_rd, "stateIn_data_V_0_sel_rd");
    sc_trace(mVcdFile, stateIn_data_V_0_sel_wr, "stateIn_data_V_0_sel_wr");
    sc_trace(mVcdFile, stateIn_data_V_0_sel, "stateIn_data_V_0_sel");
    sc_trace(mVcdFile, stateIn_data_V_0_load_A, "stateIn_data_V_0_load_A");
    sc_trace(mVcdFile, stateIn_data_V_0_load_B, "stateIn_data_V_0_load_B");
    sc_trace(mVcdFile, stateIn_data_V_0_state, "stateIn_data_V_0_state");
    sc_trace(mVcdFile, stateIn_data_V_0_state_cmp_full, "stateIn_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, stateIn_last_V_0_data_out, "stateIn_last_V_0_data_out");
    sc_trace(mVcdFile, stateIn_last_V_0_vld_in, "stateIn_last_V_0_vld_in");
    sc_trace(mVcdFile, stateIn_last_V_0_vld_out, "stateIn_last_V_0_vld_out");
    sc_trace(mVcdFile, stateIn_last_V_0_ack_in, "stateIn_last_V_0_ack_in");
    sc_trace(mVcdFile, stateIn_last_V_0_ack_out, "stateIn_last_V_0_ack_out");
    sc_trace(mVcdFile, stateIn_last_V_0_payload_A, "stateIn_last_V_0_payload_A");
    sc_trace(mVcdFile, stateIn_last_V_0_payload_B, "stateIn_last_V_0_payload_B");
    sc_trace(mVcdFile, stateIn_last_V_0_sel_rd, "stateIn_last_V_0_sel_rd");
    sc_trace(mVcdFile, stateIn_last_V_0_sel_wr, "stateIn_last_V_0_sel_wr");
    sc_trace(mVcdFile, stateIn_last_V_0_sel, "stateIn_last_V_0_sel");
    sc_trace(mVcdFile, stateIn_last_V_0_load_A, "stateIn_last_V_0_load_A");
    sc_trace(mVcdFile, stateIn_last_V_0_load_B, "stateIn_last_V_0_load_B");
    sc_trace(mVcdFile, stateIn_last_V_0_state, "stateIn_last_V_0_state");
    sc_trace(mVcdFile, stateIn_last_V_0_state_cmp_full, "stateIn_last_V_0_state_cmp_full");
    sc_trace(mVcdFile, stateOut_data_V_1_data_out, "stateOut_data_V_1_data_out");
    sc_trace(mVcdFile, stateOut_data_V_1_vld_in, "stateOut_data_V_1_vld_in");
    sc_trace(mVcdFile, stateOut_data_V_1_vld_out, "stateOut_data_V_1_vld_out");
    sc_trace(mVcdFile, stateOut_data_V_1_ack_in, "stateOut_data_V_1_ack_in");
    sc_trace(mVcdFile, stateOut_data_V_1_ack_out, "stateOut_data_V_1_ack_out");
    sc_trace(mVcdFile, stateOut_data_V_1_payload_A, "stateOut_data_V_1_payload_A");
    sc_trace(mVcdFile, stateOut_data_V_1_payload_B, "stateOut_data_V_1_payload_B");
    sc_trace(mVcdFile, stateOut_data_V_1_sel_rd, "stateOut_data_V_1_sel_rd");
    sc_trace(mVcdFile, stateOut_data_V_1_sel_wr, "stateOut_data_V_1_sel_wr");
    sc_trace(mVcdFile, stateOut_data_V_1_sel, "stateOut_data_V_1_sel");
    sc_trace(mVcdFile, stateOut_data_V_1_load_A, "stateOut_data_V_1_load_A");
    sc_trace(mVcdFile, stateOut_data_V_1_load_B, "stateOut_data_V_1_load_B");
    sc_trace(mVcdFile, stateOut_data_V_1_state, "stateOut_data_V_1_state");
    sc_trace(mVcdFile, stateOut_data_V_1_state_cmp_full, "stateOut_data_V_1_state_cmp_full");
    sc_trace(mVcdFile, stateOut_last_V_1_data_out, "stateOut_last_V_1_data_out");
    sc_trace(mVcdFile, stateOut_last_V_1_vld_in, "stateOut_last_V_1_vld_in");
    sc_trace(mVcdFile, stateOut_last_V_1_vld_out, "stateOut_last_V_1_vld_out");
    sc_trace(mVcdFile, stateOut_last_V_1_ack_in, "stateOut_last_V_1_ack_in");
    sc_trace(mVcdFile, stateOut_last_V_1_ack_out, "stateOut_last_V_1_ack_out");
    sc_trace(mVcdFile, stateOut_last_V_1_payload_A, "stateOut_last_V_1_payload_A");
    sc_trace(mVcdFile, stateOut_last_V_1_payload_B, "stateOut_last_V_1_payload_B");
    sc_trace(mVcdFile, stateOut_last_V_1_sel_rd, "stateOut_last_V_1_sel_rd");
    sc_trace(mVcdFile, stateOut_last_V_1_sel_wr, "stateOut_last_V_1_sel_wr");
    sc_trace(mVcdFile, stateOut_last_V_1_sel, "stateOut_last_V_1_sel");
    sc_trace(mVcdFile, stateOut_last_V_1_load_A, "stateOut_last_V_1_load_A");
    sc_trace(mVcdFile, stateOut_last_V_1_load_B, "stateOut_last_V_1_load_B");
    sc_trace(mVcdFile, stateOut_last_V_1_state, "stateOut_last_V_1_state");
    sc_trace(mVcdFile, stateOut_last_V_1_state_cmp_full, "stateOut_last_V_1_state_cmp_full");
    sc_trace(mVcdFile, stateIn_TDATA_blk_n, "stateIn_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, stateOut_TDATA_blk_n, "stateOut_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, stateIn_last_V_tmp_reg_121, "stateIn_last_V_tmp_reg_121");
    sc_trace(mVcdFile, p_Result_s_reg_126, "p_Result_s_reg_126");
    sc_trace(mVcdFile, tmp_82_fu_116_p1, "tmp_82_fu_116_p1");
    sc_trace(mVcdFile, tmp_82_reg_131, "tmp_82_reg_131");
    sc_trace(mVcdFile, grp_present_rounds_fu_80_ap_return, "grp_present_rounds_fu_80_ap_return");
    sc_trace(mVcdFile, grp_present_rounds_fu_80_ap_idle, "grp_present_rounds_fu_80_ap_idle");
    sc_trace(mVcdFile, grp_present_rounds_fu_80_ap_ready, "grp_present_rounds_fu_80_ap_ready");
    sc_trace(mVcdFile, grp_present_rounds_fu_80_ap_done, "grp_present_rounds_fu_80_ap_done");
    sc_trace(mVcdFile, grp_present_rounds_fu_80_ap_start, "grp_present_rounds_fu_80_ap_start");
    sc_trace(mVcdFile, grp_present_rounds_fu_80_ap_start_reg, "grp_present_rounds_fu_80_ap_start_reg");
    sc_trace(mVcdFile, ap_block_state4, "ap_block_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("present.hdltvin.dat");
    mHdltvoutHandle.open("present.hdltvout.dat");
}

present::~present() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_present_rounds_fu_80;
}

void present::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_present_rounds_fu_80_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(stateIn_data_V_0_vld_out.read(), ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            grp_present_rounds_fu_80_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_present_rounds_fu_80_ap_ready.read())) {
            grp_present_rounds_fu_80_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateIn_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_vld_out.read()))) {
            stateIn_data_V_0_sel_rd =  (sc_logic) (~stateIn_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateIn_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_ack_in.read()))) {
            stateIn_data_V_0_sel_wr =  (sc_logic) (~stateIn_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateIn_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, stateIn_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, stateIn_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_2)))) {
            stateIn_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, stateIn_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, stateIn_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_1)))) {
            stateIn_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(stateIn_data_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, stateIn_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, stateIn_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_ack_out.read()))))) {
            stateIn_data_V_0_state = ap_const_lv2_3;
        } else {
            stateIn_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateIn_last_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_vld_out.read()))) {
            stateIn_last_V_0_sel_rd =  (sc_logic) (~stateIn_last_V_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateIn_last_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_ack_in.read()))) {
            stateIn_last_V_0_sel_wr =  (sc_logic) (~stateIn_last_V_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateIn_last_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, stateIn_last_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, stateIn_last_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, stateIn_last_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, stateIn_last_V_0_state.read())))) {
            stateIn_last_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, stateIn_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, stateIn_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, stateIn_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, stateIn_last_V_0_state.read())))) {
            stateIn_last_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, stateIn_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, stateIn_last_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, stateIn_last_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, stateIn_last_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, stateIn_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_ack_out.read()))))) {
            stateIn_last_V_0_state = ap_const_lv2_3;
        } else {
            stateIn_last_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateOut_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_vld_out.read()))) {
            stateOut_data_V_1_sel_rd =  (sc_logic) (~stateOut_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateOut_data_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_ack_in.read()))) {
            stateOut_data_V_1_sel_wr =  (sc_logic) (~stateOut_data_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateOut_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, stateOut_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, stateOut_data_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, stateOut_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, stateOut_data_V_1_state.read())))) {
            stateOut_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, stateOut_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, stateOut_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, stateOut_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, stateOut_data_V_1_state.read())))) {
            stateOut_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, stateOut_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, stateOut_data_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, stateOut_data_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, stateOut_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, stateOut_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_ack_out.read()))))) {
            stateOut_data_V_1_state = ap_const_lv2_3;
        } else {
            stateOut_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateOut_last_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_vld_out.read()))) {
            stateOut_last_V_1_sel_rd =  (sc_logic) (~stateOut_last_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateOut_last_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_ack_in.read()))) {
            stateOut_last_V_1_sel_wr =  (sc_logic) (~stateOut_last_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        stateOut_last_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, stateOut_last_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, stateOut_last_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, stateOut_last_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, stateOut_last_V_1_state.read())))) {
            stateOut_last_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, stateOut_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, stateOut_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, stateOut_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, stateOut_last_V_1_state.read())))) {
            stateOut_last_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, stateOut_last_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, stateOut_last_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, stateOut_last_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, stateOut_last_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, stateOut_last_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_ack_out.read()))))) {
            stateOut_last_V_1_state = ap_const_lv2_3;
        } else {
            stateOut_last_V_1_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(stateIn_data_V_0_vld_out.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        p_Result_s_reg_126 = stateIn_data_V_0_data_out.read().range(143, 80);
        stateIn_last_V_tmp_reg_121 = stateIn_last_V_0_data_out.read();
        tmp_82_reg_131 = tmp_82_fu_116_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_load_A.read())) {
        stateIn_data_V_0_payload_A = stateIn_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_load_B.read())) {
        stateIn_data_V_0_payload_B = stateIn_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_load_A.read())) {
        stateIn_last_V_0_payload_A = stateIn_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_load_B.read())) {
        stateIn_last_V_0_payload_B = stateIn_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_load_A.read())) {
        stateOut_data_V_1_payload_A = grp_present_rounds_fu_80_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_load_B.read())) {
        stateOut_data_V_1_payload_B = grp_present_rounds_fu_80_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_load_A.read())) {
        stateOut_last_V_1_payload_A = stateIn_last_V_tmp_reg_121.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_load_B.read())) {
        stateOut_last_V_1_payload_B = stateIn_last_V_tmp_reg_121.read();
    }
}

void present::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void present::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void present::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void present::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void present::thread_ap_block_state4() {
    ap_block_state4 = (esl_seteq<1,1,1>(stateOut_last_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0));
}

void present::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(stateOut_last_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void present::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void present::thread_ap_ready() {
    if ((!(esl_seteq<1,1,1>(stateOut_last_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void present::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void present::thread_grp_present_rounds_fu_80_ap_start() {
    grp_present_rounds_fu_80_ap_start = grp_present_rounds_fu_80_ap_start_reg.read();
}

void present::thread_stateIn_TDATA_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        stateIn_TDATA_blk_n = stateIn_data_V_0_state.read()[0];
    } else {
        stateIn_TDATA_blk_n = ap_const_logic_1;
    }
}

void present::thread_stateIn_TREADY() {
    stateIn_TREADY = stateIn_last_V_0_state.read()[1];
}

void present::thread_stateIn_data_V_0_ack_in() {
    stateIn_data_V_0_ack_in = stateIn_data_V_0_state.read()[1];
}

void present::thread_stateIn_data_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(stateIn_data_V_0_vld_out.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        stateIn_data_V_0_ack_out = ap_const_logic_1;
    } else {
        stateIn_data_V_0_ack_out = ap_const_logic_0;
    }
}

void present::thread_stateIn_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_data_V_0_sel.read())) {
        stateIn_data_V_0_data_out = stateIn_data_V_0_payload_B.read();
    } else {
        stateIn_data_V_0_data_out = stateIn_data_V_0_payload_A.read();
    }
}

void present::thread_stateIn_data_V_0_load_A() {
    stateIn_data_V_0_load_A = (stateIn_data_V_0_state_cmp_full.read() & ~stateIn_data_V_0_sel_wr.read());
}

void present::thread_stateIn_data_V_0_load_B() {
    stateIn_data_V_0_load_B = (stateIn_data_V_0_sel_wr.read() & stateIn_data_V_0_state_cmp_full.read());
}

void present::thread_stateIn_data_V_0_sel() {
    stateIn_data_V_0_sel = stateIn_data_V_0_sel_rd.read();
}

void present::thread_stateIn_data_V_0_state_cmp_full() {
    stateIn_data_V_0_state_cmp_full =  (sc_logic) ((!stateIn_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(stateIn_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void present::thread_stateIn_data_V_0_vld_in() {
    stateIn_data_V_0_vld_in = stateIn_TVALID.read();
}

void present::thread_stateIn_data_V_0_vld_out() {
    stateIn_data_V_0_vld_out = stateIn_data_V_0_state.read()[0];
}

void present::thread_stateIn_last_V_0_ack_in() {
    stateIn_last_V_0_ack_in = stateIn_last_V_0_state.read()[1];
}

void present::thread_stateIn_last_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(stateIn_data_V_0_vld_out.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        stateIn_last_V_0_ack_out = ap_const_logic_1;
    } else {
        stateIn_last_V_0_ack_out = ap_const_logic_0;
    }
}

void present::thread_stateIn_last_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateIn_last_V_0_sel.read())) {
        stateIn_last_V_0_data_out = stateIn_last_V_0_payload_B.read();
    } else {
        stateIn_last_V_0_data_out = stateIn_last_V_0_payload_A.read();
    }
}

void present::thread_stateIn_last_V_0_load_A() {
    stateIn_last_V_0_load_A = (stateIn_last_V_0_state_cmp_full.read() & ~stateIn_last_V_0_sel_wr.read());
}

void present::thread_stateIn_last_V_0_load_B() {
    stateIn_last_V_0_load_B = (stateIn_last_V_0_sel_wr.read() & stateIn_last_V_0_state_cmp_full.read());
}

void present::thread_stateIn_last_V_0_sel() {
    stateIn_last_V_0_sel = stateIn_last_V_0_sel_rd.read();
}

void present::thread_stateIn_last_V_0_state_cmp_full() {
    stateIn_last_V_0_state_cmp_full =  (sc_logic) ((!stateIn_last_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(stateIn_last_V_0_state.read() != ap_const_lv2_1))[0];
}

void present::thread_stateIn_last_V_0_vld_in() {
    stateIn_last_V_0_vld_in = stateIn_TVALID.read();
}

void present::thread_stateIn_last_V_0_vld_out() {
    stateIn_last_V_0_vld_out = stateIn_last_V_0_state.read()[0];
}

void present::thread_stateOut_TDATA() {
    stateOut_TDATA = stateOut_data_V_1_data_out.read();
}

void present::thread_stateOut_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        stateOut_TDATA_blk_n = stateOut_data_V_1_state.read()[1];
    } else {
        stateOut_TDATA_blk_n = ap_const_logic_1;
    }
}

void present::thread_stateOut_TLAST() {
    stateOut_TLAST = stateOut_last_V_1_data_out.read();
}

void present::thread_stateOut_TVALID() {
    stateOut_TVALID = stateOut_last_V_1_state.read()[0];
}

void present::thread_stateOut_data_V_1_ack_in() {
    stateOut_data_V_1_ack_in = stateOut_data_V_1_state.read()[1];
}

void present::thread_stateOut_data_V_1_ack_out() {
    stateOut_data_V_1_ack_out = stateOut_TREADY.read();
}

void present::thread_stateOut_data_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_data_V_1_sel.read())) {
        stateOut_data_V_1_data_out = stateOut_data_V_1_payload_B.read();
    } else {
        stateOut_data_V_1_data_out = stateOut_data_V_1_payload_A.read();
    }
}

void present::thread_stateOut_data_V_1_load_A() {
    stateOut_data_V_1_load_A = (stateOut_data_V_1_state_cmp_full.read() & ~stateOut_data_V_1_sel_wr.read());
}

void present::thread_stateOut_data_V_1_load_B() {
    stateOut_data_V_1_load_B = (stateOut_data_V_1_sel_wr.read() & stateOut_data_V_1_state_cmp_full.read());
}

void present::thread_stateOut_data_V_1_sel() {
    stateOut_data_V_1_sel = stateOut_data_V_1_sel_rd.read();
}

void present::thread_stateOut_data_V_1_state_cmp_full() {
    stateOut_data_V_1_state_cmp_full =  (sc_logic) ((!stateOut_data_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(stateOut_data_V_1_state.read() != ap_const_lv2_1))[0];
}

void present::thread_stateOut_data_V_1_vld_in() {
    if ((!(esl_seteq<1,1,1>(grp_present_rounds_fu_80_ap_done.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        stateOut_data_V_1_vld_in = ap_const_logic_1;
    } else {
        stateOut_data_V_1_vld_in = ap_const_logic_0;
    }
}

void present::thread_stateOut_data_V_1_vld_out() {
    stateOut_data_V_1_vld_out = stateOut_data_V_1_state.read()[0];
}

void present::thread_stateOut_last_V_1_ack_in() {
    stateOut_last_V_1_ack_in = stateOut_last_V_1_state.read()[1];
}

void present::thread_stateOut_last_V_1_ack_out() {
    stateOut_last_V_1_ack_out = stateOut_TREADY.read();
}

void present::thread_stateOut_last_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, stateOut_last_V_1_sel.read())) {
        stateOut_last_V_1_data_out = stateOut_last_V_1_payload_B.read();
    } else {
        stateOut_last_V_1_data_out = stateOut_last_V_1_payload_A.read();
    }
}

void present::thread_stateOut_last_V_1_load_A() {
    stateOut_last_V_1_load_A = (stateOut_last_V_1_state_cmp_full.read() & ~stateOut_last_V_1_sel_wr.read());
}

void present::thread_stateOut_last_V_1_load_B() {
    stateOut_last_V_1_load_B = (stateOut_last_V_1_sel_wr.read() & stateOut_last_V_1_state_cmp_full.read());
}

void present::thread_stateOut_last_V_1_sel() {
    stateOut_last_V_1_sel = stateOut_last_V_1_sel_rd.read();
}

void present::thread_stateOut_last_V_1_state_cmp_full() {
    stateOut_last_V_1_state_cmp_full =  (sc_logic) ((!stateOut_last_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(stateOut_last_V_1_state.read() != ap_const_lv2_1))[0];
}

void present::thread_stateOut_last_V_1_vld_in() {
    if ((!(esl_seteq<1,1,1>(grp_present_rounds_fu_80_ap_done.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        stateOut_last_V_1_vld_in = ap_const_logic_1;
    } else {
        stateOut_last_V_1_vld_in = ap_const_logic_0;
    }
}

void present::thread_stateOut_last_V_1_vld_out() {
    stateOut_last_V_1_vld_out = stateOut_last_V_1_state.read()[0];
}

void present::thread_tmp_82_fu_116_p1() {
    tmp_82_fu_116_p1 = stateIn_data_V_0_data_out.read().range(80-1, 0);
}

void present::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(stateIn_data_V_0_vld_out.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(grp_present_rounds_fu_80_ap_done.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((!(esl_seteq<1,1,1>(stateOut_last_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(stateOut_data_V_1_ack_in.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

void present::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stateIn_TDATA\" :  \"" << stateIn_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stateIn_TVALID\" :  \"" << stateIn_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stateIn_TREADY\" :  \"" << stateIn_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stateIn_TLAST\" :  \"" << stateIn_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stateOut_TDATA\" :  \"" << stateOut_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stateOut_TVALID\" :  \"" << stateOut_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stateOut_TREADY\" :  \"" << stateOut_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stateOut_TLAST\" :  \"" << stateOut_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

