// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _orcaPLGate_HH_
#define _orcaPLGate_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct orcaPLGate : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<1> > pulse_V;
    sc_in< sc_lv<2> > PS_V;
    sc_out< sc_lv<1> > ap_return;


    // Module declarations
    orcaPLGate(sc_module_name name);
    SC_HAS_PROCESS(orcaPLGate);

    ~orcaPLGate();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > state_V;
    sc_signal< sc_lv<1> > tmp_fu_55_p3;
    sc_signal< sc_lv<1> > tmp_reg_81;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > ap_phi_mux_agg_result_V_phi_fu_48_p4;
    sc_signal< sc_lv<1> > agg_result_V_reg_44;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > pulse_V_read_read_fu_38_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_63_p1;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_phi_mux_agg_result_V_phi_fu_48_p4();
    void thread_ap_return();
    void thread_pulse_V_read_read_fu_38_p2();
    void thread_tmp_1_fu_63_p1();
    void thread_tmp_fu_55_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
