// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module present_rounds (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        plain_V,
        key_V,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    ap_const_lv80_0 = 80'd0;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] plain_V;
input  [79:0] key_V;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] sbox_V_address0;
reg    sbox_V_ce0;
wire   [7:0] sbox_V_q0;
reg   [7:0] sbox_pmt_3_V_address0;
reg    sbox_pmt_3_V_ce0;
wire   [7:0] sbox_pmt_3_V_q0;
reg   [7:0] sbox_pmt_3_V_address1;
reg    sbox_pmt_3_V_ce1;
wire   [7:0] sbox_pmt_3_V_q1;
reg   [7:0] sbox_pmt_3_V_address2;
reg    sbox_pmt_3_V_ce2;
wire   [7:0] sbox_pmt_3_V_q2;
reg   [7:0] sbox_pmt_3_V_address3;
reg    sbox_pmt_3_V_ce3;
wire   [7:0] sbox_pmt_3_V_q3;
reg   [7:0] sbox_pmt_3_V_address4;
reg    sbox_pmt_3_V_ce4;
wire   [7:0] sbox_pmt_3_V_q4;
reg   [7:0] sbox_pmt_3_V_address5;
reg    sbox_pmt_3_V_ce5;
wire   [7:0] sbox_pmt_3_V_q5;
reg   [7:0] sbox_pmt_3_V_address6;
reg    sbox_pmt_3_V_ce6;
wire   [7:0] sbox_pmt_3_V_q6;
reg   [7:0] sbox_pmt_3_V_address7;
reg    sbox_pmt_3_V_ce7;
wire   [7:0] sbox_pmt_3_V_q7;
reg   [7:0] sbox_pmt_2_V_address0;
reg    sbox_pmt_2_V_ce0;
wire   [7:0] sbox_pmt_2_V_q0;
reg   [7:0] sbox_pmt_2_V_address1;
reg    sbox_pmt_2_V_ce1;
wire   [7:0] sbox_pmt_2_V_q1;
reg   [7:0] sbox_pmt_2_V_address2;
reg    sbox_pmt_2_V_ce2;
wire   [7:0] sbox_pmt_2_V_q2;
reg   [7:0] sbox_pmt_2_V_address3;
reg    sbox_pmt_2_V_ce3;
wire   [7:0] sbox_pmt_2_V_q3;
reg   [7:0] sbox_pmt_2_V_address4;
reg    sbox_pmt_2_V_ce4;
wire   [7:0] sbox_pmt_2_V_q4;
reg   [7:0] sbox_pmt_2_V_address5;
reg    sbox_pmt_2_V_ce5;
wire   [7:0] sbox_pmt_2_V_q5;
reg   [7:0] sbox_pmt_2_V_address6;
reg    sbox_pmt_2_V_ce6;
wire   [7:0] sbox_pmt_2_V_q6;
reg   [7:0] sbox_pmt_2_V_address7;
reg    sbox_pmt_2_V_ce7;
wire   [7:0] sbox_pmt_2_V_q7;
reg   [7:0] sbox_pmt_1_V_address0;
reg    sbox_pmt_1_V_ce0;
wire   [7:0] sbox_pmt_1_V_q0;
reg   [7:0] sbox_pmt_1_V_address1;
reg    sbox_pmt_1_V_ce1;
wire   [7:0] sbox_pmt_1_V_q1;
reg   [7:0] sbox_pmt_1_V_address2;
reg    sbox_pmt_1_V_ce2;
wire   [7:0] sbox_pmt_1_V_q2;
reg   [7:0] sbox_pmt_1_V_address3;
reg    sbox_pmt_1_V_ce3;
wire   [7:0] sbox_pmt_1_V_q3;
reg   [7:0] sbox_pmt_1_V_address4;
reg    sbox_pmt_1_V_ce4;
wire   [7:0] sbox_pmt_1_V_q4;
reg   [7:0] sbox_pmt_1_V_address5;
reg    sbox_pmt_1_V_ce5;
wire   [7:0] sbox_pmt_1_V_q5;
reg   [7:0] sbox_pmt_1_V_address6;
reg    sbox_pmt_1_V_ce6;
wire   [7:0] sbox_pmt_1_V_q6;
reg   [7:0] sbox_pmt_1_V_address7;
reg    sbox_pmt_1_V_ce7;
wire   [7:0] sbox_pmt_1_V_q7;
reg   [7:0] sbox_pmt_0_V_address0;
reg    sbox_pmt_0_V_ce0;
wire   [7:0] sbox_pmt_0_V_q0;
reg   [7:0] sbox_pmt_0_V_address1;
reg    sbox_pmt_0_V_ce1;
wire   [7:0] sbox_pmt_0_V_q1;
reg   [7:0] sbox_pmt_0_V_address2;
reg    sbox_pmt_0_V_ce2;
wire   [7:0] sbox_pmt_0_V_q2;
reg   [7:0] sbox_pmt_0_V_address3;
reg    sbox_pmt_0_V_ce3;
wire   [7:0] sbox_pmt_0_V_q3;
reg   [7:0] sbox_pmt_0_V_address4;
reg    sbox_pmt_0_V_ce4;
wire   [7:0] sbox_pmt_0_V_q4;
reg   [7:0] sbox_pmt_0_V_address5;
reg    sbox_pmt_0_V_ce5;
wire   [7:0] sbox_pmt_0_V_q5;
reg   [7:0] sbox_pmt_0_V_address6;
reg    sbox_pmt_0_V_ce6;
wire   [7:0] sbox_pmt_0_V_q6;
reg   [7:0] sbox_pmt_0_V_address7;
reg    sbox_pmt_0_V_ce7;
wire   [7:0] sbox_pmt_0_V_q7;
reg   [7:0] r_V_204_trunc_reg_2247;
reg   [15:0] tmp_reg_2252;
reg   [7:0] r_V_207_trunc_reg_2257;
reg   [7:0] r_V_210_trunc_reg_2263;
reg   [7:0] r_V_213_trunc_reg_2268;
reg   [7:0] r_V_216_trunc_reg_2273;
reg   [7:0] r_V_219_trunc_reg_2278;
wire   [2:0] tmp_3_fu_1578_p1;
reg   [2:0] tmp_3_reg_2283;
reg   [4:0] r_V_s_reg_2288;
reg   [7:0] r_V_225_trunc_reg_2293;
reg   [3:0] tmp_2_reg_2303;
wire   [79:0] p_Result_83_fu_1827_p5;
wire    ap_CS_fsm_state2;
wire   [63:0] p_Result_84_fu_1871_p33;
wire    ap_CS_fsm_state3;
wire   [0:0] exitcond_fu_1939_p2;
wire   [7:0] r_V_326_trunc_fu_2035_p2;
reg   [7:0] r_V_326_trunc_reg_2641;
reg   [3:0] tmp_8_reg_2651;
wire   [10:0] tmp_81_fu_2066_p1;
reg   [10:0] tmp_81_reg_2656;
reg   [39:0] tmp_62_reg_2661;
reg   [12:0] tmp_63_reg_2666;
wire   [5:0] round_counter_V_fu_2090_p2;
reg   [5:0] round_counter_V_reg_2671;
wire   [63:0] p_Result_85_fu_2158_p33;
wire    ap_CS_fsm_state4;
wire   [79:0] p_Result_86_fu_2235_p7;
reg   [63:0] p_Val2_9_reg_835;
reg   [79:0] p_Val2_10_reg_844;
reg   [5:0] t_V_reg_853;
wire   [63:0] phitmp_cast_fu_1612_p1;
wire   [63:0] p_Result_s_16_fu_1627_p1;
wire   [63:0] p_Result_16_fu_1635_p1;
wire   [63:0] p_Result_17_fu_1643_p1;
wire   [63:0] p_Result_18_fu_1651_p1;
wire   [63:0] p_Result_19_fu_1659_p1;
wire   [63:0] p_Result_20_fu_1667_p1;
wire   [63:0] p_Result_21_fu_1675_p1;
wire   [63:0] p_Result_23_fu_1683_p1;
wire   [63:0] p_Result_27_fu_1955_p1;
wire   [63:0] p_Result_28_fu_1963_p1;
wire   [63:0] p_Result_45_fu_1971_p1;
wire   [63:0] p_Result_62_fu_1979_p1;
wire   [63:0] p_Result_63_fu_1987_p1;
wire   [63:0] p_Result_64_fu_1995_p1;
wire   [63:0] p_Result_65_fu_2003_p1;
wire   [63:0] p_Result_66_fu_2011_p1;
wire   [63:0] phitmp1_cast_fu_2051_p1;
wire   [7:0] grp_fu_1124_p4;
wire   [7:0] grp_fu_1114_p4;
wire   [7:0] grp_fu_1150_p4;
wire   [7:0] grp_fu_1140_p4;
wire   [7:0] grp_fu_1176_p4;
wire   [7:0] grp_fu_1166_p4;
wire   [7:0] grp_fu_1202_p4;
wire   [7:0] grp_fu_1192_p4;
wire   [7:0] grp_fu_1228_p4;
wire   [7:0] grp_fu_1218_p4;
wire   [7:0] grp_fu_1254_p4;
wire   [7:0] grp_fu_1244_p4;
wire   [7:0] grp_fu_1280_p4;
wire   [7:0] grp_fu_1270_p4;
wire   [7:0] p_Result_1_fu_1316_p4;
wire   [7:0] p_Result_s_fu_1306_p4;
wire   [7:0] p_Result_3_fu_1342_p4;
wire   [7:0] p_Result_2_fu_1332_p4;
wire   [7:0] p_Result_5_fu_1368_p4;
wire   [7:0] p_Result_4_fu_1358_p4;
wire   [7:0] p_Result_7_fu_1394_p4;
wire   [7:0] p_Result_6_fu_1384_p4;
wire   [7:0] p_Result_9_fu_1420_p4;
wire   [7:0] p_Result_8_fu_1410_p4;
wire   [7:0] p_Result_11_fu_1446_p4;
wire   [7:0] p_Result_10_fu_1436_p4;
wire   [7:0] p_Result_13_fu_1472_p4;
wire   [7:0] p_Result_12_fu_1462_p4;
wire   [7:0] p_Result_14_fu_1492_p4;
wire   [7:0] tmp_1_fu_1488_p1;
wire   [3:0] phitmp_fu_1602_p4;
wire   [7:0] loc_V_trunc_fu_1326_p2;
wire   [7:0] loc_V_1_trunc_fu_1352_p2;
wire   [7:0] loc_V_2_trunc_fu_1378_p2;
wire   [7:0] loc_V_3_trunc_fu_1404_p2;
wire   [7:0] loc_V_4_trunc_fu_1430_p2;
wire   [7:0] loc_V_5_trunc_fu_1456_p2;
wire   [7:0] loc_V_6_trunc_fu_1482_p2;
wire   [7:0] loc_V_7_trunc_fu_1502_p2;
wire   [79:0] p_Result_74_fu_1691_p5;
wire   [79:0] p_Result_75_fu_1702_p5;
wire   [79:0] p_Result_76_fu_1713_p5;
wire   [79:0] p_Result_77_fu_1724_p5;
wire   [79:0] p_Result_78_fu_1735_p5;
wire   [79:0] p_Result_79_fu_1746_p5;
wire   [7:0] r_V_222_trunc_fu_1757_p3;
wire   [79:0] p_Result_80_fu_1763_p5;
wire   [3:0] tmp_9_fu_1786_p1;
wire   [3:0] grp_fu_864_p4;
wire   [3:0] tmp_4_fu_1790_p2;
wire   [79:0] p_Result_81_fu_1775_p5;
wire   [7:0] tmp_6_fu_1795_p3;
wire   [7:0] r_V_229_trunc_fu_1815_p2;
wire   [79:0] p_Result_82_fu_1803_p5;
wire   [15:0] tmp_7_fu_1820_p3;
wire   [1:0] grp_fu_874_p4;
wire   [1:0] grp_fu_884_p4;
wire   [1:0] grp_fu_894_p4;
wire   [1:0] tmp_14_fu_1839_p1;
wire   [1:0] grp_fu_904_p4;
wire   [1:0] grp_fu_914_p4;
wire   [1:0] grp_fu_924_p4;
wire   [1:0] tmp_60_fu_1843_p1;
wire   [1:0] grp_fu_934_p4;
wire   [1:0] grp_fu_944_p4;
wire   [1:0] grp_fu_954_p4;
wire   [1:0] tmp_61_fu_1847_p1;
wire   [1:0] grp_fu_964_p4;
wire   [1:0] grp_fu_974_p4;
wire   [1:0] grp_fu_984_p4;
wire   [1:0] tmp_64_fu_1851_p1;
wire   [1:0] grp_fu_994_p4;
wire   [1:0] grp_fu_1004_p4;
wire   [1:0] grp_fu_1014_p4;
wire   [1:0] tmp_65_fu_1855_p1;
wire   [1:0] grp_fu_1024_p4;
wire   [1:0] grp_fu_1034_p4;
wire   [1:0] grp_fu_1044_p4;
wire   [1:0] tmp_66_fu_1859_p1;
wire   [1:0] grp_fu_1054_p4;
wire   [1:0] grp_fu_1064_p4;
wire   [1:0] grp_fu_1074_p4;
wire   [1:0] tmp_67_fu_1863_p1;
wire   [1:0] grp_fu_1084_p4;
wire   [1:0] grp_fu_1094_p4;
wire   [1:0] grp_fu_1104_p4;
wire   [1:0] tmp_68_fu_1867_p1;
wire   [7:0] grp_fu_1296_p4;
wire   [7:0] tmp_70_fu_1945_p1;
wire   [7:0] grp_fu_1134_p2;
wire   [7:0] grp_fu_1160_p2;
wire   [7:0] grp_fu_1186_p2;
wire   [7:0] grp_fu_1212_p2;
wire   [7:0] grp_fu_1238_p2;
wire   [7:0] grp_fu_1264_p2;
wire   [7:0] grp_fu_1290_p2;
wire   [7:0] loc_V_24_trunc_fu_1949_p2;
wire   [4:0] tmp_79_fu_2019_p1;
wire   [6:0] r_V_fu_2023_p3;
wire   [7:0] r_V_cast_fu_2031_p1;
wire   [3:0] phitmp1_fu_2041_p4;
wire   [7:0] tmp_69_fu_2096_p1;
wire   [7:0] loc_V_46_trunc_fu_2100_p2;
wire   [1:0] tmp_71_fu_2126_p1;
wire   [1:0] tmp_72_fu_2130_p1;
wire   [1:0] tmp_73_fu_2134_p1;
wire   [1:0] tmp_74_fu_2138_p1;
wire   [1:0] tmp_75_fu_2142_p1;
wire   [1:0] tmp_76_fu_2146_p1;
wire   [1:0] tmp_77_fu_2150_p1;
wire   [1:0] tmp_78_fu_2154_p1;
wire   [3:0] tmp_80_fu_2226_p1;
wire   [3:0] tmp_s_fu_2230_p2;
wire   [63:0] p_Result_87_fu_2106_p9;
reg   [63:0] ap_return_preg;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_return_preg = 64'd0;
end

present_rounds_sbbkb #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
sbox_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_V_address0),
    .ce0(sbox_V_ce0),
    .q0(sbox_V_q0)
);

present_rounds_sbcud #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sbox_pmt_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_pmt_3_V_address0),
    .ce0(sbox_pmt_3_V_ce0),
    .q0(sbox_pmt_3_V_q0),
    .address1(sbox_pmt_3_V_address1),
    .ce1(sbox_pmt_3_V_ce1),
    .q1(sbox_pmt_3_V_q1),
    .address2(sbox_pmt_3_V_address2),
    .ce2(sbox_pmt_3_V_ce2),
    .q2(sbox_pmt_3_V_q2),
    .address3(sbox_pmt_3_V_address3),
    .ce3(sbox_pmt_3_V_ce3),
    .q3(sbox_pmt_3_V_q3),
    .address4(sbox_pmt_3_V_address4),
    .ce4(sbox_pmt_3_V_ce4),
    .q4(sbox_pmt_3_V_q4),
    .address5(sbox_pmt_3_V_address5),
    .ce5(sbox_pmt_3_V_ce5),
    .q5(sbox_pmt_3_V_q5),
    .address6(sbox_pmt_3_V_address6),
    .ce6(sbox_pmt_3_V_ce6),
    .q6(sbox_pmt_3_V_q6),
    .address7(sbox_pmt_3_V_address7),
    .ce7(sbox_pmt_3_V_ce7),
    .q7(sbox_pmt_3_V_q7)
);

present_rounds_sbdEe #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sbox_pmt_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_pmt_2_V_address0),
    .ce0(sbox_pmt_2_V_ce0),
    .q0(sbox_pmt_2_V_q0),
    .address1(sbox_pmt_2_V_address1),
    .ce1(sbox_pmt_2_V_ce1),
    .q1(sbox_pmt_2_V_q1),
    .address2(sbox_pmt_2_V_address2),
    .ce2(sbox_pmt_2_V_ce2),
    .q2(sbox_pmt_2_V_q2),
    .address3(sbox_pmt_2_V_address3),
    .ce3(sbox_pmt_2_V_ce3),
    .q3(sbox_pmt_2_V_q3),
    .address4(sbox_pmt_2_V_address4),
    .ce4(sbox_pmt_2_V_ce4),
    .q4(sbox_pmt_2_V_q4),
    .address5(sbox_pmt_2_V_address5),
    .ce5(sbox_pmt_2_V_ce5),
    .q5(sbox_pmt_2_V_q5),
    .address6(sbox_pmt_2_V_address6),
    .ce6(sbox_pmt_2_V_ce6),
    .q6(sbox_pmt_2_V_q6),
    .address7(sbox_pmt_2_V_address7),
    .ce7(sbox_pmt_2_V_ce7),
    .q7(sbox_pmt_2_V_q7)
);

present_rounds_sbeOg #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sbox_pmt_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_pmt_1_V_address0),
    .ce0(sbox_pmt_1_V_ce0),
    .q0(sbox_pmt_1_V_q0),
    .address1(sbox_pmt_1_V_address1),
    .ce1(sbox_pmt_1_V_ce1),
    .q1(sbox_pmt_1_V_q1),
    .address2(sbox_pmt_1_V_address2),
    .ce2(sbox_pmt_1_V_ce2),
    .q2(sbox_pmt_1_V_q2),
    .address3(sbox_pmt_1_V_address3),
    .ce3(sbox_pmt_1_V_ce3),
    .q3(sbox_pmt_1_V_q3),
    .address4(sbox_pmt_1_V_address4),
    .ce4(sbox_pmt_1_V_ce4),
    .q4(sbox_pmt_1_V_q4),
    .address5(sbox_pmt_1_V_address5),
    .ce5(sbox_pmt_1_V_ce5),
    .q5(sbox_pmt_1_V_q5),
    .address6(sbox_pmt_1_V_address6),
    .ce6(sbox_pmt_1_V_ce6),
    .q6(sbox_pmt_1_V_q6),
    .address7(sbox_pmt_1_V_address7),
    .ce7(sbox_pmt_1_V_ce7),
    .q7(sbox_pmt_1_V_q7)
);

present_rounds_sbfYi #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sbox_pmt_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_pmt_0_V_address0),
    .ce0(sbox_pmt_0_V_ce0),
    .q0(sbox_pmt_0_V_q0),
    .address1(sbox_pmt_0_V_address1),
    .ce1(sbox_pmt_0_V_ce1),
    .q1(sbox_pmt_0_V_q1),
    .address2(sbox_pmt_0_V_address2),
    .ce2(sbox_pmt_0_V_ce2),
    .q2(sbox_pmt_0_V_q2),
    .address3(sbox_pmt_0_V_address3),
    .ce3(sbox_pmt_0_V_ce3),
    .q3(sbox_pmt_0_V_q3),
    .address4(sbox_pmt_0_V_address4),
    .ce4(sbox_pmt_0_V_ce4),
    .q4(sbox_pmt_0_V_q4),
    .address5(sbox_pmt_0_V_address5),
    .ce5(sbox_pmt_0_V_ce5),
    .q5(sbox_pmt_0_V_q5),
    .address6(sbox_pmt_0_V_address6),
    .ce6(sbox_pmt_0_V_ce6),
    .q6(sbox_pmt_0_V_q6),
    .address7(sbox_pmt_0_V_address7),
    .ce7(sbox_pmt_0_V_ce7),
    .q7(sbox_pmt_0_V_q7)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if (((exitcond_fu_1939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_return_preg <= p_Result_87_fu_2106_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_10_reg_844 <= p_Result_86_fu_2235_p7;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_10_reg_844 <= p_Result_83_fu_1827_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_9_reg_835 <= p_Result_85_fu_2158_p33;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_9_reg_835 <= p_Result_84_fu_1871_p33;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        t_V_reg_853 <= round_counter_V_reg_2671;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        t_V_reg_853 <= 6'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        r_V_204_trunc_reg_2247 <= {{key_V[34:27]}};
        r_V_207_trunc_reg_2257 <= {{key_V[42:35]}};
        r_V_210_trunc_reg_2263 <= {{key_V[50:43]}};
        r_V_213_trunc_reg_2268 <= {{key_V[58:51]}};
        r_V_216_trunc_reg_2273 <= {{key_V[66:59]}};
        r_V_219_trunc_reg_2278 <= {{key_V[74:67]}};
        r_V_225_trunc_reg_2293 <= {{key_V[10:3]}};
        r_V_s_reg_2288 <= {{key_V[79:75]}};
        tmp_2_reg_2303 <= {{key_V[14:11]}};
        tmp_3_reg_2283 <= tmp_3_fu_1578_p1;
        tmp_reg_2252 <= {{key_V[34:19]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_1939_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        r_V_326_trunc_reg_2641 <= r_V_326_trunc_fu_2035_p2;
        round_counter_V_reg_2671 <= round_counter_V_fu_2090_p2;
        tmp_62_reg_2661 <= {{p_Val2_10_reg_844[79:40]}};
        tmp_63_reg_2666 <= {{p_Val2_10_reg_844[31:19]}};
        tmp_81_reg_2656 <= tmp_81_fu_2066_p1;
        tmp_8_reg_2651 <= {{p_Val2_10_reg_844[14:11]}};
    end
end

always @ (*) begin
    if ((((exitcond_fu_1939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_1939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_1939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_return = p_Result_87_fu_2106_p9;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_V_address0 = phitmp1_cast_fu_2051_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_V_address0 = phitmp_cast_fu_1612_p1;
    end else begin
        sbox_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_V_ce0 = 1'b1;
    end else begin
        sbox_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address0 = p_Result_62_fu_1979_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address0 = p_Result_18_fu_1651_p1;
    end else begin
        sbox_pmt_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address1 = p_Result_66_fu_2011_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address1 = p_Result_23_fu_1683_p1;
    end else begin
        sbox_pmt_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address2 = p_Result_27_fu_1955_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address2 = p_Result_s_16_fu_1627_p1;
    end else begin
        sbox_pmt_0_V_address2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address3 = p_Result_63_fu_1987_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address3 = p_Result_19_fu_1659_p1;
    end else begin
        sbox_pmt_0_V_address3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address4 = p_Result_28_fu_1963_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address4 = p_Result_16_fu_1635_p1;
    end else begin
        sbox_pmt_0_V_address4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address5 = p_Result_64_fu_1995_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address5 = p_Result_20_fu_1667_p1;
    end else begin
        sbox_pmt_0_V_address5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address6 = p_Result_45_fu_1971_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address6 = p_Result_17_fu_1643_p1;
    end else begin
        sbox_pmt_0_V_address6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_0_V_address7 = p_Result_65_fu_2003_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_0_V_address7 = p_Result_21_fu_1675_p1;
    end else begin
        sbox_pmt_0_V_address7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce0 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce1 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce2 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce3 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce4 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce5 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce6 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_0_V_ce7 = 1'b1;
    end else begin
        sbox_pmt_0_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address0 = p_Result_45_fu_1971_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address0 = p_Result_17_fu_1643_p1;
    end else begin
        sbox_pmt_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address1 = p_Result_65_fu_2003_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address1 = p_Result_21_fu_1675_p1;
    end else begin
        sbox_pmt_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address2 = p_Result_62_fu_1979_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address2 = p_Result_18_fu_1651_p1;
    end else begin
        sbox_pmt_1_V_address2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address3 = p_Result_66_fu_2011_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address3 = p_Result_23_fu_1683_p1;
    end else begin
        sbox_pmt_1_V_address3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address4 = p_Result_27_fu_1955_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address4 = p_Result_s_16_fu_1627_p1;
    end else begin
        sbox_pmt_1_V_address4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address5 = p_Result_63_fu_1987_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address5 = p_Result_19_fu_1659_p1;
    end else begin
        sbox_pmt_1_V_address5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address6 = p_Result_28_fu_1963_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address6 = p_Result_16_fu_1635_p1;
    end else begin
        sbox_pmt_1_V_address6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_1_V_address7 = p_Result_64_fu_1995_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_1_V_address7 = p_Result_20_fu_1667_p1;
    end else begin
        sbox_pmt_1_V_address7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce0 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce1 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce2 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce3 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce4 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce5 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce6 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_1_V_ce7 = 1'b1;
    end else begin
        sbox_pmt_1_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address0 = p_Result_28_fu_1963_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address0 = p_Result_16_fu_1635_p1;
    end else begin
        sbox_pmt_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address1 = p_Result_64_fu_1995_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address1 = p_Result_20_fu_1667_p1;
    end else begin
        sbox_pmt_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address2 = p_Result_45_fu_1971_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address2 = p_Result_17_fu_1643_p1;
    end else begin
        sbox_pmt_2_V_address2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address3 = p_Result_65_fu_2003_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address3 = p_Result_21_fu_1675_p1;
    end else begin
        sbox_pmt_2_V_address3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address4 = p_Result_62_fu_1979_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address4 = p_Result_18_fu_1651_p1;
    end else begin
        sbox_pmt_2_V_address4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address5 = p_Result_66_fu_2011_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address5 = p_Result_23_fu_1683_p1;
    end else begin
        sbox_pmt_2_V_address5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address6 = p_Result_27_fu_1955_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address6 = p_Result_s_16_fu_1627_p1;
    end else begin
        sbox_pmt_2_V_address6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_2_V_address7 = p_Result_63_fu_1987_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_2_V_address7 = p_Result_19_fu_1659_p1;
    end else begin
        sbox_pmt_2_V_address7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce0 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce1 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce2 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce3 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce4 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce5 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce6 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_2_V_ce7 = 1'b1;
    end else begin
        sbox_pmt_2_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address0 = p_Result_27_fu_1955_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address0 = p_Result_s_16_fu_1627_p1;
    end else begin
        sbox_pmt_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address1 = p_Result_63_fu_1987_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address1 = p_Result_19_fu_1659_p1;
    end else begin
        sbox_pmt_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address2 = p_Result_28_fu_1963_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address2 = p_Result_16_fu_1635_p1;
    end else begin
        sbox_pmt_3_V_address2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address3 = p_Result_64_fu_1995_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address3 = p_Result_20_fu_1667_p1;
    end else begin
        sbox_pmt_3_V_address3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address4 = p_Result_45_fu_1971_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address4 = p_Result_17_fu_1643_p1;
    end else begin
        sbox_pmt_3_V_address4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address5 = p_Result_65_fu_2003_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address5 = p_Result_21_fu_1675_p1;
    end else begin
        sbox_pmt_3_V_address5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address6 = p_Result_62_fu_1979_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address6 = p_Result_18_fu_1651_p1;
    end else begin
        sbox_pmt_3_V_address6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sbox_pmt_3_V_address7 = p_Result_66_fu_2011_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sbox_pmt_3_V_address7 = p_Result_23_fu_1683_p1;
    end else begin
        sbox_pmt_3_V_address7 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce0 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce1 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce2 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce3 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce4 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce5 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce6 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sbox_pmt_3_V_ce7 = 1'b1;
    end else begin
        sbox_pmt_3_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond_fu_1939_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign exitcond_fu_1939_p2 = ((t_V_reg_853 == 6'd32) ? 1'b1 : 1'b0);

assign grp_fu_1004_p4 = {{sbox_pmt_0_V_q4[5:4]}};

assign grp_fu_1014_p4 = {{sbox_pmt_3_V_q4[3:2]}};

assign grp_fu_1024_p4 = {{sbox_pmt_1_V_q5[7:6]}};

assign grp_fu_1034_p4 = {{sbox_pmt_0_V_q5[5:4]}};

assign grp_fu_1044_p4 = {{sbox_pmt_3_V_q5[3:2]}};

assign grp_fu_1054_p4 = {{sbox_pmt_2_V_q6[7:6]}};

assign grp_fu_1064_p4 = {{sbox_pmt_1_V_q6[5:4]}};

assign grp_fu_1074_p4 = {{sbox_pmt_0_V_q6[3:2]}};

assign grp_fu_1084_p4 = {{sbox_pmt_2_V_q7[7:6]}};

assign grp_fu_1094_p4 = {{sbox_pmt_1_V_q7[5:4]}};

assign grp_fu_1104_p4 = {{sbox_pmt_0_V_q7[3:2]}};

assign grp_fu_1114_p4 = {{p_Val2_9_reg_835[63:56]}};

assign grp_fu_1124_p4 = {{p_Val2_10_reg_844[79:72]}};

assign grp_fu_1134_p2 = (grp_fu_1124_p4 ^ grp_fu_1114_p4);

assign grp_fu_1140_p4 = {{p_Val2_9_reg_835[55:48]}};

assign grp_fu_1150_p4 = {{p_Val2_10_reg_844[71:64]}};

assign grp_fu_1160_p2 = (grp_fu_1150_p4 ^ grp_fu_1140_p4);

assign grp_fu_1166_p4 = {{p_Val2_9_reg_835[47:40]}};

assign grp_fu_1176_p4 = {{p_Val2_10_reg_844[63:56]}};

assign grp_fu_1186_p2 = (grp_fu_1176_p4 ^ grp_fu_1166_p4);

assign grp_fu_1192_p4 = {{p_Val2_9_reg_835[39:32]}};

assign grp_fu_1202_p4 = {{p_Val2_10_reg_844[55:48]}};

assign grp_fu_1212_p2 = (grp_fu_1202_p4 ^ grp_fu_1192_p4);

assign grp_fu_1218_p4 = {{p_Val2_9_reg_835[31:24]}};

assign grp_fu_1228_p4 = {{p_Val2_10_reg_844[47:40]}};

assign grp_fu_1238_p2 = (grp_fu_1228_p4 ^ grp_fu_1218_p4);

assign grp_fu_1244_p4 = {{p_Val2_9_reg_835[23:16]}};

assign grp_fu_1254_p4 = {{p_Val2_10_reg_844[39:32]}};

assign grp_fu_1264_p2 = (grp_fu_1254_p4 ^ grp_fu_1244_p4);

assign grp_fu_1270_p4 = {{p_Val2_9_reg_835[15:8]}};

assign grp_fu_1280_p4 = {{p_Val2_10_reg_844[31:24]}};

assign grp_fu_1290_p2 = (grp_fu_1280_p4 ^ grp_fu_1270_p4);

assign grp_fu_1296_p4 = {{p_Val2_10_reg_844[23:16]}};

assign grp_fu_864_p4 = {{sbox_V_q0[7:4]}};

assign grp_fu_874_p4 = {{sbox_pmt_3_V_q0[7:6]}};

assign grp_fu_884_p4 = {{sbox_pmt_2_V_q0[5:4]}};

assign grp_fu_894_p4 = {{sbox_pmt_1_V_q0[3:2]}};

assign grp_fu_904_p4 = {{sbox_pmt_3_V_q1[7:6]}};

assign grp_fu_914_p4 = {{sbox_pmt_2_V_q1[5:4]}};

assign grp_fu_924_p4 = {{sbox_pmt_1_V_q1[3:2]}};

assign grp_fu_934_p4 = {{sbox_pmt_0_V_q2[7:6]}};

assign grp_fu_944_p4 = {{sbox_pmt_3_V_q2[5:4]}};

assign grp_fu_954_p4 = {{sbox_pmt_2_V_q2[3:2]}};

assign grp_fu_964_p4 = {{sbox_pmt_0_V_q3[7:6]}};

assign grp_fu_974_p4 = {{sbox_pmt_3_V_q3[5:4]}};

assign grp_fu_984_p4 = {{sbox_pmt_2_V_q3[3:2]}};

assign grp_fu_994_p4 = {{sbox_pmt_1_V_q4[7:6]}};

assign loc_V_1_trunc_fu_1352_p2 = (p_Result_3_fu_1342_p4 ^ p_Result_2_fu_1332_p4);

assign loc_V_24_trunc_fu_1949_p2 = (tmp_70_fu_1945_p1 ^ grp_fu_1296_p4);

assign loc_V_2_trunc_fu_1378_p2 = (p_Result_5_fu_1368_p4 ^ p_Result_4_fu_1358_p4);

assign loc_V_3_trunc_fu_1404_p2 = (p_Result_7_fu_1394_p4 ^ p_Result_6_fu_1384_p4);

assign loc_V_46_trunc_fu_2100_p2 = (tmp_69_fu_2096_p1 ^ grp_fu_1296_p4);

assign loc_V_4_trunc_fu_1430_p2 = (p_Result_9_fu_1420_p4 ^ p_Result_8_fu_1410_p4);

assign loc_V_5_trunc_fu_1456_p2 = (p_Result_11_fu_1446_p4 ^ p_Result_10_fu_1436_p4);

assign loc_V_6_trunc_fu_1482_p2 = (p_Result_13_fu_1472_p4 ^ p_Result_12_fu_1462_p4);

assign loc_V_7_trunc_fu_1502_p2 = (tmp_1_fu_1488_p1 ^ p_Result_14_fu_1492_p4);

assign loc_V_trunc_fu_1326_p2 = (p_Result_s_fu_1306_p4 ^ p_Result_1_fu_1316_p4);

assign p_Result_10_fu_1436_p4 = {{plain_V[23:16]}};

assign p_Result_11_fu_1446_p4 = {{key_V[39:32]}};

assign p_Result_12_fu_1462_p4 = {{plain_V[15:8]}};

assign p_Result_13_fu_1472_p4 = {{key_V[31:24]}};

assign p_Result_14_fu_1492_p4 = {{key_V[23:16]}};

assign p_Result_16_fu_1635_p1 = loc_V_1_trunc_fu_1352_p2;

assign p_Result_17_fu_1643_p1 = loc_V_2_trunc_fu_1378_p2;

assign p_Result_18_fu_1651_p1 = loc_V_3_trunc_fu_1404_p2;

assign p_Result_19_fu_1659_p1 = loc_V_4_trunc_fu_1430_p2;

assign p_Result_1_fu_1316_p4 = {{key_V[79:72]}};

assign p_Result_20_fu_1667_p1 = loc_V_5_trunc_fu_1456_p2;

assign p_Result_21_fu_1675_p1 = loc_V_6_trunc_fu_1482_p2;

assign p_Result_23_fu_1683_p1 = loc_V_7_trunc_fu_1502_p2;

assign p_Result_27_fu_1955_p1 = grp_fu_1134_p2;

assign p_Result_28_fu_1963_p1 = grp_fu_1160_p2;

assign p_Result_2_fu_1332_p4 = {{plain_V[55:48]}};

assign p_Result_3_fu_1342_p4 = {{key_V[71:64]}};

assign p_Result_45_fu_1971_p1 = grp_fu_1186_p2;

assign p_Result_4_fu_1358_p4 = {{plain_V[47:40]}};

assign p_Result_5_fu_1368_p4 = {{key_V[63:56]}};

assign p_Result_62_fu_1979_p1 = grp_fu_1212_p2;

assign p_Result_63_fu_1987_p1 = grp_fu_1238_p2;

assign p_Result_64_fu_1995_p1 = grp_fu_1264_p2;

assign p_Result_65_fu_2003_p1 = grp_fu_1290_p2;

assign p_Result_66_fu_2011_p1 = loc_V_24_trunc_fu_1949_p2;

assign p_Result_6_fu_1384_p4 = {{plain_V[39:32]}};

assign p_Result_74_fu_1691_p5 = {{ap_const_lv80_0[79:16]}, {tmp_reg_2252}};

assign p_Result_75_fu_1702_p5 = {{p_Result_74_fu_1691_p5[79:24]}, {r_V_207_trunc_reg_2257}, {p_Result_74_fu_1691_p5[15:0]}};

assign p_Result_76_fu_1713_p5 = {{p_Result_75_fu_1702_p5[79:32]}, {r_V_210_trunc_reg_2263}, {p_Result_75_fu_1702_p5[23:0]}};

assign p_Result_77_fu_1724_p5 = {{p_Result_76_fu_1713_p5[79:40]}, {r_V_213_trunc_reg_2268}, {p_Result_76_fu_1713_p5[31:0]}};

assign p_Result_78_fu_1735_p5 = {{p_Result_77_fu_1724_p5[79:48]}, {r_V_216_trunc_reg_2273}, {p_Result_77_fu_1724_p5[39:0]}};

assign p_Result_79_fu_1746_p5 = {{p_Result_78_fu_1735_p5[79:56]}, {r_V_219_trunc_reg_2278}, {p_Result_78_fu_1735_p5[47:0]}};

assign p_Result_7_fu_1394_p4 = {{key_V[55:48]}};

assign p_Result_80_fu_1763_p5 = {{p_Result_79_fu_1746_p5[79:64]}, {r_V_222_trunc_fu_1757_p3}, {p_Result_79_fu_1746_p5[55:0]}};

assign p_Result_81_fu_1775_p5 = {{p_Result_80_fu_1763_p5[79:72]}, {r_V_225_trunc_reg_2293}, {p_Result_80_fu_1763_p5[63:0]}};

assign p_Result_82_fu_1803_p5 = {{tmp_6_fu_1795_p3}, {p_Result_81_fu_1775_p5[71:0]}};

assign p_Result_83_fu_1827_p5 = {{p_Result_82_fu_1803_p5[79:24]}, {tmp_7_fu_1820_p3}, {p_Result_82_fu_1803_p5[7:0]}};

assign p_Result_84_fu_1871_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{grp_fu_874_p4}, {grp_fu_884_p4}}, {grp_fu_894_p4}}, {tmp_14_fu_1839_p1}}, {grp_fu_904_p4}}, {grp_fu_914_p4}}, {grp_fu_924_p4}}, {tmp_60_fu_1843_p1}}, {grp_fu_934_p4}}, {grp_fu_944_p4}}, {grp_fu_954_p4}}, {tmp_61_fu_1847_p1}}, {grp_fu_964_p4}}, {grp_fu_974_p4}}, {grp_fu_984_p4}}, {tmp_64_fu_1851_p1}}, {grp_fu_994_p4}}, {grp_fu_1004_p4}}, {grp_fu_1014_p4}}, {tmp_65_fu_1855_p1}}, {grp_fu_1024_p4}}, {grp_fu_1034_p4}}, {grp_fu_1044_p4}}, {tmp_66_fu_1859_p1}}, {grp_fu_1054_p4}}, {grp_fu_1064_p4}}, {grp_fu_1074_p4}}, {tmp_67_fu_1863_p1}}, {grp_fu_1084_p4}}, {grp_fu_1094_p4}}, {grp_fu_1104_p4}}, {tmp_68_fu_1867_p1}};

assign p_Result_85_fu_2158_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{grp_fu_874_p4}, {grp_fu_884_p4}}, {grp_fu_894_p4}}, {tmp_71_fu_2126_p1}}, {grp_fu_904_p4}}, {grp_fu_914_p4}}, {grp_fu_924_p4}}, {tmp_72_fu_2130_p1}}, {grp_fu_934_p4}}, {grp_fu_944_p4}}, {grp_fu_954_p4}}, {tmp_73_fu_2134_p1}}, {grp_fu_964_p4}}, {grp_fu_974_p4}}, {grp_fu_984_p4}}, {tmp_74_fu_2138_p1}}, {grp_fu_994_p4}}, {grp_fu_1004_p4}}, {grp_fu_1014_p4}}, {tmp_75_fu_2142_p1}}, {grp_fu_1024_p4}}, {grp_fu_1034_p4}}, {grp_fu_1044_p4}}, {tmp_76_fu_2146_p1}}, {grp_fu_1054_p4}}, {grp_fu_1064_p4}}, {grp_fu_1074_p4}}, {tmp_77_fu_2150_p1}}, {grp_fu_1084_p4}}, {grp_fu_1094_p4}}, {grp_fu_1104_p4}}, {tmp_78_fu_2154_p1}};

assign p_Result_86_fu_2235_p7 = {{{{{{grp_fu_864_p4}, {tmp_s_fu_2230_p2}}, {tmp_81_reg_2656}}, {tmp_62_reg_2661}}, {r_V_326_trunc_reg_2641}}, {tmp_63_reg_2666}};

assign p_Result_87_fu_2106_p9 = {{{{{{{{grp_fu_1134_p2}, {grp_fu_1160_p2}}, {grp_fu_1186_p2}}, {grp_fu_1212_p2}}, {grp_fu_1238_p2}}, {grp_fu_1264_p2}}, {grp_fu_1290_p2}}, {loc_V_46_trunc_fu_2100_p2}};

assign p_Result_8_fu_1410_p4 = {{plain_V[31:24]}};

assign p_Result_9_fu_1420_p4 = {{key_V[47:40]}};

assign p_Result_s_16_fu_1627_p1 = loc_V_trunc_fu_1326_p2;

assign p_Result_s_fu_1306_p4 = {{plain_V[63:56]}};

assign phitmp1_cast_fu_2051_p1 = phitmp1_fu_2041_p4;

assign phitmp1_fu_2041_p4 = {{p_Val2_10_reg_844[18:15]}};

assign phitmp_cast_fu_1612_p1 = phitmp_fu_1602_p4;

assign phitmp_fu_1602_p4 = {{key_V[18:15]}};

assign r_V_222_trunc_fu_1757_p3 = {{tmp_3_reg_2283}, {r_V_s_reg_2288}};

assign r_V_229_trunc_fu_1815_p2 = (r_V_204_trunc_reg_2247 ^ 8'd128);

assign r_V_326_trunc_fu_2035_p2 = (r_V_cast_fu_2031_p1 ^ grp_fu_1254_p4);

assign r_V_cast_fu_2031_p1 = r_V_fu_2023_p3;

assign r_V_fu_2023_p3 = {{tmp_79_fu_2019_p1}, {2'd0}};

assign round_counter_V_fu_2090_p2 = (6'd1 + t_V_reg_853);

assign tmp_14_fu_1839_p1 = sbox_pmt_0_V_q0[1:0];

assign tmp_1_fu_1488_p1 = plain_V[7:0];

assign tmp_3_fu_1578_p1 = key_V[2:0];

assign tmp_4_fu_1790_p2 = (tmp_9_fu_1786_p1 | tmp_2_reg_2303);

assign tmp_60_fu_1843_p1 = sbox_pmt_0_V_q1[1:0];

assign tmp_61_fu_1847_p1 = sbox_pmt_1_V_q2[1:0];

assign tmp_64_fu_1851_p1 = sbox_pmt_1_V_q3[1:0];

assign tmp_65_fu_1855_p1 = sbox_pmt_2_V_q4[1:0];

assign tmp_66_fu_1859_p1 = sbox_pmt_2_V_q5[1:0];

assign tmp_67_fu_1863_p1 = sbox_pmt_3_V_q6[1:0];

assign tmp_68_fu_1867_p1 = sbox_pmt_3_V_q7[1:0];

assign tmp_69_fu_2096_p1 = p_Val2_9_reg_835[7:0];

assign tmp_6_fu_1795_p3 = {{grp_fu_864_p4}, {tmp_4_fu_1790_p2}};

assign tmp_70_fu_1945_p1 = p_Val2_9_reg_835[7:0];

assign tmp_71_fu_2126_p1 = sbox_pmt_0_V_q0[1:0];

assign tmp_72_fu_2130_p1 = sbox_pmt_0_V_q1[1:0];

assign tmp_73_fu_2134_p1 = sbox_pmt_1_V_q2[1:0];

assign tmp_74_fu_2138_p1 = sbox_pmt_1_V_q3[1:0];

assign tmp_75_fu_2142_p1 = sbox_pmt_2_V_q4[1:0];

assign tmp_76_fu_2146_p1 = sbox_pmt_2_V_q5[1:0];

assign tmp_77_fu_2150_p1 = sbox_pmt_3_V_q6[1:0];

assign tmp_78_fu_2154_p1 = sbox_pmt_3_V_q7[1:0];

assign tmp_79_fu_2019_p1 = t_V_reg_853[4:0];

assign tmp_7_fu_1820_p3 = {{r_V_207_trunc_reg_2257}, {r_V_229_trunc_fu_1815_p2}};

assign tmp_80_fu_2226_p1 = sbox_V_q0[3:0];

assign tmp_81_fu_2066_p1 = p_Val2_10_reg_844[10:0];

assign tmp_9_fu_1786_p1 = sbox_V_q0[3:0];

assign tmp_s_fu_2230_p2 = (tmp_8_reg_2651 | tmp_80_fu_2226_p1);

endmodule //present_rounds
