// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsad_match.h"

extern XSad_match_Config XSad_match_ConfigTable[];

XSad_match_Config *XSad_match_LookupConfig(u16 DeviceId) {
	XSad_match_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSAD_MATCH_NUM_INSTANCES; Index++) {
		if (XSad_match_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSad_match_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSad_match_Initialize(XSad_match *InstancePtr, u16 DeviceId) {
	XSad_match_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSad_match_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSad_match_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

