// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSAD_MATCH_H
#define XSAD_MATCH_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsad_match_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_BaseAddress;
} XSad_match_Config;
#endif

typedef struct {
    u32 Ctrl_BaseAddress;
    u32 IsReady;
} XSad_match;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSad_match_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSad_match_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSad_match_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSad_match_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSad_match_Initialize(XSad_match *InstancePtr, u16 DeviceId);
XSad_match_Config* XSad_match_LookupConfig(u16 DeviceId);
int XSad_match_CfgInitialize(XSad_match *InstancePtr, XSad_match_Config *ConfigPtr);
#else
int XSad_match_Initialize(XSad_match *InstancePtr, const char* InstanceName);
int XSad_match_Release(XSad_match *InstancePtr);
#endif

void XSad_match_Start(XSad_match *InstancePtr);
u32 XSad_match_IsDone(XSad_match *InstancePtr);
u32 XSad_match_IsIdle(XSad_match *InstancePtr);
u32 XSad_match_IsReady(XSad_match *InstancePtr);
void XSad_match_EnableAutoRestart(XSad_match *InstancePtr);
void XSad_match_DisableAutoRestart(XSad_match *InstancePtr);


void XSad_match_InterruptGlobalEnable(XSad_match *InstancePtr);
void XSad_match_InterruptGlobalDisable(XSad_match *InstancePtr);
void XSad_match_InterruptEnable(XSad_match *InstancePtr, u32 Mask);
void XSad_match_InterruptDisable(XSad_match *InstancePtr, u32 Mask);
void XSad_match_InterruptClear(XSad_match *InstancePtr, u32 Mask);
u32 XSad_match_InterruptGetEnabled(XSad_match *InstancePtr);
u32 XSad_match_InterruptGetStatus(XSad_match *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
