// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsad_match.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSad_match_CfgInitialize(XSad_match *InstancePtr, XSad_match_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSad_match_Start(XSad_match *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL) & 0x80;
    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSad_match_IsDone(XSad_match *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSad_match_IsIdle(XSad_match *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSad_match_IsReady(XSad_match *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSad_match_EnableAutoRestart(XSad_match *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL, 0x80);
}

void XSad_match_DisableAutoRestart(XSad_match *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_AP_CTRL, 0);
}

void XSad_match_InterruptGlobalEnable(XSad_match *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_GIE, 1);
}

void XSad_match_InterruptGlobalDisable(XSad_match *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_GIE, 0);
}

void XSad_match_InterruptEnable(XSad_match *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_IER);
    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_IER, Register | Mask);
}

void XSad_match_InterruptDisable(XSad_match *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_IER);
    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_IER, Register & (~Mask));
}

void XSad_match_InterruptClear(XSad_match *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSad_match_WriteReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_ISR, Mask);
}

u32 XSad_match_InterruptGetEnabled(XSad_match *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_IER);
}

u32 XSad_match_InterruptGetStatus(XSad_match *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSad_match_ReadReg(InstancePtr->Ctrl_BaseAddress, XSAD_MATCH_CTRL_ADDR_ISR);
}

